# 1. Database Connection (Pointing to your local Docker Container)
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_management_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=cloud_engineer_app
spring.datasource.password=app_secure_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Spring Data JPA Settings (Automated Table Creation)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Security Settings (Development Credentials)
spring.security.user.name=admin
spring.security.user.password=secret123